[features]
seeds = false
skip-lint = false

[programs.localnet]
identity_program = "7mzcZ1jT5gKrqYdHuPk3ex8oBHHZpzicYjFDZZhETvL3"

[programs.mainnet]
identity_program = "7mzcZ1jT5gKrqYdHuPk3ex8oBHHZpzicYjFDZZhETvL3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/.config/solana/id.json"

[scripts]
test-init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/init.ts"
test-vouch = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/vouch.ts"
test-identity-manager = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/identity_manager.ts"
test-init-identity = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/init_identity.ts"
test-set-price = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/set_price.ts"
test-set-vouch-reward = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/identity-program/set_vouch_reward.ts"